baseURL: "https://adenchen27.github.io/" 
title: Aden Chen
theme: PaperMod
pagination:
  disableAliases: true
  pagerSize: 20

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
    # description: "Undergraduate student at the University of Chicago studying Mathematics and Economics. "
    author: Aden Chen
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "Jan 02, 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Aden Chen
          subtitle: "Undergraduate at the University of Chicago studying Mathematics and Economics. "
          imageUrl: "Aden-Profile.jpg"
          imageWidth: 175
          imageHeight: 175
          imageTitle: Aden Chen
          buttons:
            - name: Papers
              url: papers/
            # - name: Projects
            #   url: projects/
            - name: Resume
              url: resume.pdf
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: resume.pdf
        - name: Email
          url: mailto:adenc@uchicago.com
        - name: GitHub
          url: https://github.com/AdenChen27
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@alexandermccallsmithoffici9000
        # - name: Twitter
        #   url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Aden Chen"
      icon: favicon.ico
      iconHeight: 18


# params:
#   env: production # to enable google analytics, opengraph, twitter-cards and schema.
#   title: Aden Chen
#   description: "Aden Chen's website"
#   keywords: [Portfolio]
#   author: Aden Chen
#   images: ["Aden-Profile.png"]
#   DateFormat: "January 2, 2006"
#   defaultTheme: auto # dark, light
#   disableThemeToggle: false

#   ShowReadingTime: true
#   ShowShareButtons: true
#   ShowPostNavLinks: true
#   ShowBreadCrumbs: true
#   ShowCodeCopyButtons: false
#   ShowWordCount: true
#   ShowRssButtonInSectionTermList: true
#   UseHugoToc: true
#   disableSpecial1stPost: false
#   disableScrollToTop: false
#   comments: false
#   hidemeta: false
#   hideSummary: false
#   showtoc: false
#   tocopen: false

#   assets:
#     # disableHLJS: true # to disable highlight.js
#     # disableFingerprinting: true
#     favicon: "<link / abs url>"
#     favicon16x16: "<link / abs url>"
#     favicon32x32: "<link / abs url>"
#     apple_touch_icon: "<link / abs url>"
#     safari_pinned_tab: "<link / abs url>"

#   label:
#     text: "Home"
#     icon: /apple-touch-icon.png
#     iconHeight: 35

#   # profile-mode
#   profileMode:
#     enabled: false # needs to be explicitly set
#     title: ExampleSite
#     subtitle: "This is subtitle"
#     imageUrl: "<img location>"
#     imageWidth: 120
#     imageHeight: 120
#     imageTitle: my image
#     buttons:
#       - name: Posts
#         url: posts
#       - name: Tags
#         url: tags

#   # home-info mode
#   homeInfoParams:
#     Title: "Hi there \U0001F44B"
#     Content: Welcome to my blog

#   socialIcons:
#     - name: x
#       url: "https://x.com/"
#     - name: stackoverflow
#       url: "https://stackoverflow.com"
#     - name: github
#       url: "https://github.com/"

#   analytics:
#     google:
#       SiteVerificationTag: "XYZabc"
#     bing:
#       SiteVerificationTag: "XYZabc"
#     yandex:
#       SiteVerificationTag: "XYZabc"

#   cover:
#     hidden: true # hide everywhere but not in structured data
#     hiddenInList: true # hide on list pages and home
#     hiddenInSingle: true # hide on single page

#   editPost:
#     URL: "https://github.com/<path_to_repo>/content"
#     Text: "Suggest Changes" # edit text
#     appendFilePath: true # to append file path to Edit link

#   # for search
#   # https://fusejs.io/api/options.html
#   fuseOpts:
#     isCaseSensitive: false
#     shouldSort: true
#     location: 0
#     distance: 1000
#     threshold: 0.4
#     minMatchCharLength: 0
#     limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
#     keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: example
      name: example.org
      url: https://example.org
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
