function demo() {

document.getElementById("essay").innerText = `

Gender Differences in Psychology

The (2001) psychological differences (1997) between men and(1998) women are well-established and widely documented. These (test, 1973, 2001, 2000, n.d.; see also: test1, 2007, 2010; test2, 1999) differences can be seen in areas as influential in our lives as a career choice, with women showing greater interest in careers requiring artistic and social skills (Stoet & Geary, 2018), and communication style, with men being more goal-oriented and assertive (Newman et al., 2008; Maharani et al., 2020). Or, the differences can reveal themselves in areas as trivial as how men and women chose to alleviate boredom while sitting in an empty room for fifteen minutes with nothing to do except administer electric shocks to themselves: men more often opted to shock themselves (Wilson et al., 2014).

These (see Koehler, 2016, for more detail) differences manifest themselves across a spectrum of areas, such as the ability to discern different facial expressions (Babchuk et al., 1985), performance change in competitive environments (Gneezy et al., 2003), aggression (Hay, a2007), self-esteem, subjective well-being (Schmitt et al., 2016), basic human values (Fors Connolly et al., 2019; Schwartz & Rubel, 2005), and empathy (Klein & Hodges, 2001). The differences in personality, measured using the big five personality traits, even hold true across different cultures, with women in multiple countries scoring higher in neuroticism, agreeableness, and extraversion compared to men (Costa et al., 2001; McCrae & Terracciano, 2005; Schmitt et al., 2008; Weisberg et al., 2011).

There is (dgyuewgyugwue, sahufaui) extensive documentation that men and women are indeed psychologically different. But does it matter? If we are to subscribe to John Locke’s underlying principle of individualism to ensure both men and women have the equality of opportunities in society (Butler, 1978), then understanding the causes for these psychological differences is critically important to design policies that effectively promote gender equality.

Environmental causes account for a considerable amount of the gender psychological differences, especially regarding abilities and skills. For instance, Alan et al. (2019) discovered that while children did not exhibit gender differences in leadership willingness, a large gender gap was found among adolescents. They suggested that this may be caused by adolescent girls’ sharp decline in social confidence resulting from social pressure. Social system and gender roles may be another significant cause. For example, Gneezy et al. (2009) found that in the matrilineal Khasi society, much different from results found in western areas, women are more prone to compete.

One way to understand how the environment contributes to the gender difference in psychology is by analyzing stereotype threat: the fear of living up to the negative stereotypes about one’s group. The common stereotype threat of boys being better at math particularly harmed girls. Walton et al. (2013) estimated that stereotype threat is responsible for 57-94% of the gender performance gap in the SAT math section.

Stereotype threat contributes to performance differences even when the stereotypes are implicit. In a study by Huguet and Régner (2007), researchers selected middle school students with highly selective math grades and divided them into two groups. While the researchers provided both groups with the same test of replicating figures from memory, one group was told it was a “geometry test” and the other group a “drawing test.” By naming the test “geometry test”, the test activated a stereotype threat disfavoring girls and caused them to underperform boys. However, girls told that the test was a “drawing test” outperformed boys. Similarly, in Klein and Hodges’ (2001) experiment, the gender performance gap on an empathic accuracy test increased when the test was presented as measuring interpersonal ability.

In addition to the performance gap, stereotype threats can also affect people’s decisions. Dekhtyar et al. (2018) conducted a longitudinal study on individuals from Sweden starting from the age of 16. They found that men and women tend to exhibit a technical and a language advantage, respectively, and choose their occupations and education accordingly. However, men and women with similar strengths take different routes for their education and career, with both men and women choosing paths that better fit their gender description. Their choices are likely also influenced by external forces such as stereotype threat caused by gender expectations.

Stereotype threat is especially damaging to people who believe that one’s attributes are innate and constant, who, under mindset theory, lean toward having an entity theory of intelligence. Those having an incremental theory of intelligence, on the other hand, believe that abilities can improve over time. When viewing different matters, one can have different mindsets. Believing that one’s abilities are innate and inflexible, entity theorists tend to think that negative stereotypes indicate their failure in the future and are more likely to retreat when facing obstacles (Dweck, 2008, 2012; Froehlich et al., 2016; Hong et al., 1999). Not only does having an entity theory facilitate stereotype threat, but it is also partly caused by the related stereotypes (Laurell et al., 2021; see also Froehlich et al., 2016). This may be a major force contributing to female students’ higher entity theory endorsement regarding sports (Prot et al., 2014) abilities and, especially, mathematics (Todor, 2014) strengths, dissuading them from continuing their studies in mathematics and science (Dweck, 2007).

However, environmental causes alone do not explain all aspects of the psychological gender differences. For instance, infants are hardly affected by social norms; however, they nonetheless exhibit gender differences in psychology that parallel those of adults (Alexander & Wilcox, 2012; Fausto-Sterling et al., 2012). Although different parenting behavior based on sex - the most visible being that parents tend to spend more time talking to daughters than to sons (Leaper et al., 1998; see also Fausto-Sterling et al., 2012) - may be part of the cause, they are generally minimal (Endendijk et al., 2016). To fully exclude the effects of social norms, researchers would have to control human infants’ social interaction, but it would hardly be ethically possible. However, researchers can draw on experiments on nonhuman primates like macaques, whose infants exhibit many sex differences that resemble those of humans. In a study by Simpson et al. (2016), the macaque infants raised in homogenous environments still exhibit sex differences in response to social stimuli, suggesting that they, and possibly humans as well, do have innate psychological differences. Evidence also supports that genes greatly influence personalities (Bouchard, Jr. & Loehlin, 2001).

Moreover, diving deeper into the relative cross-culture gender differences reveals the gender-equality paradox: the finding that gender differences are more pronounced in areas with more progressive sex-role ideologies. Although in modern countries sex role differences are emphasized less, they ascribe more adjectives to either men or women, suggesting greater gender differentiation (Costa et al., 2001). Scholars have found similar phenomena when analyzing gender differences in preference (Falk & Hermle, 2018), basic human values (Fors Connolly et al., 2019; Schwartz & Rubel, 2005), self-esteem and depression (Schmitt et al., 2016), and occupation interests (Stoet & Geary, 2018). This, too, suggests that some of the gender differences are intrinsic and stem from biological differences. Just like height difference is larger in richer places due to the resulting nutrition gap (Peñuelas et al., 2017), having better and more equal access to resources in more egalitarian places may make innate psychological gender differences easier to surface, as people can make choices reflecting their preferences (Falk & Hermle, 2018). More freedom leads to people showing greater differences, as is suggested by how gender differences in texting language use are typically larger on tasks with fewer language use constraints (Newman et al., 2008).

How, then, do biological differences cause innate psychological differences? Part of the answer lies in the different sex hormones. Studies show that prenatal androgens - hormones responsible for male characteristics - have a masculinizing effect on male fetuses’ brains, affecting their personalities, interests, and even cognitive abilities (Berenbaum & Beltz, 2011; Schmitt et al., 2016). Evidence also showed that exposure to atypical levels of androgens in gestation is related to male-typical play preferences (Richards & Browne, 2022) and physical aggressiveness (Hines et al., 2015).

Evolutionary psychology suggests that the root cause for these intrinsic variations is human evolution. It predicts that men and women are naturally different in areas they face different adaptive problems while similar in all others (Buss, 1995). For example, as the primary caretaker for infants, female primates may be selected to be more caring (Babchuk et al., 1985). Likewise, males’ higher level of aggressiveness may result from ancestral intersexual competition (Buss, 1991). Most of these intrinsic gender psychological differences developed during the hunter-gatherer era (Schmitt et al., 2016). Schmitt offered another explanation for the gender-equality paradox: The gender differences widen in more egalitarian societies because they are psychologically more similar to the hunter-gather ones (Schmitt, 2005). As societies transitioned into the agricultural and monotheistic era, resource distribution became increasingly unequal and sex differences were suppressed. As societies now become more egalitarian, however, they resemble the hunter-gather era more and sex differences, therefore, are more visible (Schmitt et al., 2008).

Knowing how the environment affects psychological gender differences offers more direct ways to help tackle gender inequality. For instance, recognizing that gender differences in willingness to make risky leadership decisions likely stem from social pressure during adolescence (Alan et al., 2019), policymakers and teachers can focus on reducing social pressure. Knowing how stereotype threat and one’s implicit theory of intelligence play a part in the gender performance gap in STEM subjects, researchers and educators can think about ways to reduce stereotype threat or promote an increment theory of intelligence to reduce the gender gap. Studies showed that praising students’ efforts instead of their ability and teaching them about how the brain forms connections when one learns encourages an incremental theory of intelligence and significantly narrows the gender gap (Dweck, 2007). In addition, providing external incentives may help in combating stereotype threats, as is evident in a study by Klein and Hodges (2001) about gender differences in empathy, wherein the gender performance gap vanished after a monetary incentive was provided. Reducing the idea of competition, especially that of women and men competing against each other, may also help to gender performance disparity (Gneezy et al., 2003). Although biological differences may be impractical to eliminate, they give hints about what social measures have the most potential to tackle inequalities. If, for example, men and women naturally prefer different jobs, then in addition to reducing the gender representation gap in each occupation, society should perhaps also try to narrow the salary/recognition gap in different occupation types.

Furthermore, understanding how psychological differences are influenced by hormones gives us insight into policies extending beyond promoting gender equality. In particular, testosterone might be responsible for the higher violence rate among men, promoting violent behavior in those prone to aggression by increasing the feeling of associated reward (Booth et al., 2006; Geniole et al., 2019; Mims, 2007). Men’s testosterone levels peak when they are young adults, increase when they divorce, and decrease when they marry and become fathers (Booth et al., 2006; Mazur & Michalek, 1998). Thus, a sex ratio skewed towards men produces more unmarried young men with higher levels of testosterone, which may consequently lead to a more violent society. By analyzing provincial data on violence rate and sex ratio, Edlund et al. (2013) concluded that one-seventh of the crime rate increase in the 1990s in China can be attributed to the surplus of young men facilitated by the one-child policy. Historians have also hypothesized that the skewed sex ratio in western America during the westward movement escalated violence against Native Americans and women (Hvistendahl, 2012). Knowledge about these potential impacts can help governments predict and prevent future conflicts related to skewed sex ratios.

Determining to what extent innate differences and social environments influence gender differences in psychology is indispensable in making policies. Good measures can hardly be devised without knowing both the intrinsic and extrinsic causes.

`;



document.getElementById("references").innerText = `
Alan, S., Ertac, S., Kubilay, E., & Loranth, G. (2019). Understanding Gender Differences in Leadership. The Economic Journal. https://doi.org/10.1093/ej/uez050
Alexander, G. M., & Wilcox, T. (2012). Sex Differences in Early Infancy. Child Development Perspectives, n/a. https://doi.org/10.1111/j.1750-8606.2012.00247.x
Babchuk, W. A., Hames, R. B., & Thompson, R. A. (1985). Sex differences in the recognition of infant facial expressions of emotion: The primary caretaker hypothesis. Ethology and Sociobiology, 6(2), 89–101. https://doi.org/10.1016/0162-3095(85)90002-0
Berenbaum, S. A., & Beltz, A. M. (2011). Sexual differentiation of human behavior: Effects of prenatal and pubertal organizational hormones. Frontiers in Neuroendocrinology, 32(2), 183–200. https://doi.org/10.1016/j.yfrne.2011.03.001
Boaler, J. (2013). Ability and Mathematics: the mindset revolution that is reshaping education. FORUM, 55(1), 143. https://doi.org/10.2304/forum.2013.55.1.143
Booth, A., Granger, D. A., Mazur, A., & Kivlighan, K. T. (2006). Testosterone and Social Behavior. Social Forces, 85(1), 167–191. https://doi.org/10.1353/sof.2006.0116
Bouchard, Jr., T. J., & Loehlin, J. C. (2001). Genes, Evolution, and Personality. Behavior Genetics, 31(3), 243–273. https://doi.org/10.1023/a:1012294324713
Buss, D. M. (1991). Evolutionary Personality Psychology. Annual Review of Psychology, 42(1), 459–491. https://doi.org/10.1146/annurev.ps.42.020191.002331
Buss, D. M. (1995). Psychological sex differences: Origins through sexual selection. American Psychologist, 50(3), 164–168. https://doi.org/10.1037/0003-066x.50.3.164
Buss, D. M., & Schmitt, D. P. (2011). Evolutionary Psychology and Feminism. Sex Roles, 64(9–10), 768–787. https://doi.org/10.1007/s11199-011-9987-3
Costa, P. T., Terracciano, A., & McCrae, R. R. (2001). Gender differences in personality traits across cultures: Robust and surprising findings. Journal of Personality and Social Psychology, 81(2), 322–331. https://doi.org/10.1037/0022-3514.81.2.322
Dekhtyar, S., Weber, D., Helgertz, J., & Herlitz, A. (2018). Sex differences in academic strengths contribute to gender segregation in education and occupation: A longitudinal examination of 167,776 individuals. Intelligence, 67, 84–92. https://doi.org/10.1016/j.intell.2017.11.007
del Giudice, M., Booth, T., & Irwing, P. (2012). The Distance Between Mars and Venus: Measuring Global Sex Differences in Personality. PLoS ONE, 7(1), e29265. https://doi.org/10.1371/journal.pone.0029265
Digest of Education Statistics Table 226.10. (2020, December). National Center for Education Statistics. Retrieved June 12, 2022, from https://nces.ed.gov/programs/digest/d20/tables/dt20_226.10.asp
Digest of Education Statistics Table 226.50. (2021, March). National Center for Education Statistics. Retrieved June 12, 2022, from https://nces.ed.gov/programs/digest/d20/tables/dt20_226.50.asp
Dweck, C. S. (2007). Is Math a Gift? Beliefs That Put Females at Risk. In S. J. Ceci & W. M. Williams (Eds.), Why Aren’t More Women in Science?: Top Researchers Debate the Evidence (pp. 47–55). Amer Psychological Association. https://doi.org/10.1037/11546-004
Dweck, C. S. (2008). Can Personality Be Changed? The Role of Beliefs in Personality and Change. Current Directions in Psychological Science, 17(6), 391–394. https://doi.org/10.1111/j.1467-8721.2008.00612.x
Dweck, C. S. (2012). Mindsets and human nature: Promoting change in the Middle East, the schoolyard, the racial divide, and willpower. American Psychologist, 67(8), 614–622. https://doi.org/10.1037/a0029783
Eagly, A. H., Eaton, A., Rose, S. M., Riger, S., & McHugh, M. C. (2012). Feminism and psychology: Analysis of a half-century of research on women and gender. American Psychologist, 67(3), 211–230. https://doi.org/10.1037/a0027260
Eagly, A. H., & Wood, W. (2011). Feminism and the Evolution of Sex Differences and Similarities. Sex Roles, 64(9–10), 758–767. https://doi.org/10.1007/s11199-011-9949-9
Easterbrook, M. J., & Hadden, I. R. (2020). Tackling Educational Inequalities with Social Psychology: Identities, Contexts, and Interventions. Social Issues and Policy Review, 15(1), 180–236. https://doi.org/10.1111/sipr.12070
Edlund, L., Li, H., Yi, J., & Zhang, J. (2013). Sex Ratios and Crime: Evidence from China. The Review of Economics and Statistics, 95(5), 1520–1534. https://doi.org/10.1162/rest_a_00356
Endendijk, J. J., Groeneveld, M. G., Bakermans-Kranenburg, M. J., & Mesman, J. (2016). Gender-Differentiated Parenting Revisited: Meta-Analysis Reveals Very Few Differences in Parental Control of Boys and Girls. PLOS ONE, 11(7), e0159193. https://doi.org/10.1371/journal.pone.0159193
Eriksson, K., Björnstjerna, M., & Vartanova, I. (2020). The Relation Between Gender Egalitarian Values and Gender Differences in Academic Achievement. Frontiers in Psychology, 11. https://doi.org/10.3389/fpsyg.2020.00236
Falk, A., & Hermle, J. (2018). Relationship of gender differences in preferences to economic development and gender equality. Science, 362(6412). https://doi.org/10.1126/science.aas9899
Fausto-Sterling, A., Coll, C. G., & Lamarre, M. (2012). Sexing the baby: Part 1 – What do we really know about sex differentiation in the first three years of life? Social Science & Medicine, 74(11), 1684–1692. https://doi.org/10.1016/j.socscimed.2011.05.051
Fischer, A., Halperin, E., Canetti, D., & Jasini, A. (2018). Why We Hate. Emotion Review, 10(4), 309–320. https://doi.org/10.1177/1754073917751229
Fors Connolly, F., Goossen, M., & Hjerm, M. (2019). Does Gender Equality Cause Gender Differences in Values? Reassessing the Gender-Equality-Personality Paradox. Sex Roles, 83(1–2), 101–113. https://doi.org/10.1007/s11199-019-01097-x
Froehlich, L., Martiny, S. E., Deaux, K., Goetz, T., & Mok, S. Y. (2016). Being smart or getting smarter: Implicit theory of intelligence moderates stereotype threat and stereotype lift effects. British Journal of Social Psychology, 55(3), 564–587. https://doi.org/10.1111/bjso.12144
Geniole, S. N., Procyshyn, T. L., Marley, N., Ortiz, T. L., Bird, B. M., Marcellus, A. L., Welker, K. M., Bonin, P. L., Goldfarb, B., Watson, N. V., & Carré, J. M. (2019). Using a Psychopharmacogenetic Approach To Identify the Pathways Through Which—and the People for Whom—Testosterone Promotes Aggression. Psychological Science, 30(4), 481–494. https://doi.org/10.1177/0956797619826970
Gneezy, U., Leonard, K. L., & List, J. A. (2009). Gender Differences in Competition: Evidence From a Matrilineal and a Patriarchal Society. Econometrica, 77(5), 1637–1664. https://doi.org/10.3982/ecta6690
Gneezy, U., Niederle, M., & Rustichini, A. (2003). Performance in Competitive Environments: Gender Differences. The Quarterly Journal of Economics, 118(3), 1049–1074. https://doi.org/10.1162/00335530360698496
Gray, J. (1994). Men Are from Mars, Women Are from Venus: A Practical Guide for Improving Communication and Getting What You Want in Your Relationships (1ST ed.). HarperCollins.
Hamrick, K. (2021). Women, Minorities, and Persons with Disabilities in Science and Engineering: 2021. National Science Foundation. https://ncses.nsf.gov/pubs/nsf21321/
Hay, D. F. (2007). The gradual emergence of sex differences in aggression: alternative hypotheses. Psychological Medicine, 37(11), 1527–1537. https://doi.org/10.1017/s0033291707000165
Hines, M., Constantinescu, M., & Spencer, D. (2015). Early androgen exposure and human gender development. Biology of Sex Differences, 6(1). https://doi.org/10.1186/s13293-015-0022-1
Hong, Y. Y., Chiu, C. Y., Dweck, C. S., Lin, D. M. S., & Wan, W. (1999). Implicit theories, attributions, and coping: A meaning system approach. Journal of Personality and Social Psychology, 77(3), 588–599. https://doi.org/10.1037/0022-3514.77.3.588
Huguet, P., & Régner, I. (2007). Stereotype threat among schoolgirls in quasi-ordinary classroom circumstances. Journal of Educational Psychology, 99(3), 545–560. https://doi.org/10.1037/0022-0663.99.3.545
Hvistendahl, M. (2012). Unnatural Selection. PublicAffairs.
Klein, K. J. K., & Hodges, S. D. (2001). Gender Differences, Motivation, and Empathic Accuracy: When it Pays to Understand. Personality and Social Psychology Bulletin, 27(6), 720–730. https://doi.org/10.1177/0146167201276007
Laurell, J., Seitamaa, A., Sormunen, K., Seitamaa-Hakkarainen, P., Korhonen, T., & Hakkarainen, K. (2021). A socio-cultural approach to growth-mindset pedagogy: Maker-pedagogy as a tool for developing a next-generation growth mindset. In E. Kuusisto, M. Ubani, P. Nokelainen, & A. Toom (Eds.), Good Teachers for Tomorrow’s Schools Purpose, Values, and Talents in Education (Moral Development and Citizenship Education) (pp. 296–312). BRILL. https://doi.org/10.1163/9789004465008_016
Leaper, C., Anderson, K. J., & Sanders, P. (1998). Moderators of gender effects on parents’ talk to their children: A meta-analysis. Developmental Psychology, 34(1), 3–27. https://doi.org/10.1037/0012-1649.34.1.3
Leaper, C., & Ayres, M. M. (2007). A Meta-Analytic Review of Gender Variations in Adults’ Language Use: Talkativeness, Affiliative Speech, and Assertive Speech. Personality and Social Psychology Review, 11(4), 328–363. https://doi.org/10.1177/1088868307302221
Maharani, S., Mujiyanto, J., & Warsono, W. (2020). The Relations between Male and Female Participants in Using Assertive Speech Acts for Interactions in The Ellen DeGeneres Show. English Education Journal, 10(2), 234–241. https://doi.org/10.15294/eej.v10i1.35145
Mazur, A., & Michalek, J. (1998). Marriage, Divorce, and Male Testosterone. Social Forces, 77(1), 315. https://doi.org/10.2307/3006019
McCrae, R. R., & Terracciano, A. (2005). Universal Features of Personality Traits From the Observer’s Perspective: Data From 50 Cultures. Journal of Personality and Social Psychology, 88(3), 547–561. https://doi.org/10.1037/0022-3514.88.3.547
Miller, C. C. (2018, March 5). Americans Might No Longer Prefer Sons Over Daughters. The New York Times. Retrieved June 27, 2022, from https://www.nytimes.com/2018/03/05/upshot/americans-might-no-longer-prefer-sons-over-daughters.html
Miller, D. I., Eagly, A. H., & Linn, M. C. (2015). Women’s representation in science predicts national gender-science stereotypes: Evidence from 66 nations. Journal of Educational Psychology, 107(3), 631–644. https://doi.org/10.1037/edu0000005
Mims, C. (2007, July 5). Strange but True: Testosterone Alone Does Not Cause Violence. Scientific American. https://www.scientificamerican.com/article/strange-but-true-testosterone-alone-doesnt-cause-violence/
Newman, M. L., Groom, C. J., Handelman, L. D., & Pennebaker, J. W. (2008). Gender Differences in Language Use: An Analysis of 14,000 Text Samples. Discourse Processes, 45(3), 211–236. https://doi.org/10.1080/01638530802073712
Peñuelas, J., Janssens, I. A., Ciais, P., Obersteiner, M., Krisztin, T., Piao, S., & Sardans, J. (2017). Increasing gap in human height between rich and poor countries associated to their different intakes of N and P. Scientific Reports, 7(1). https://doi.org/10.1038/s41598-017-17880-3
Prot, F., Balent, B., & Bosnar, K. (2014). Gender Differences in Sport Mindset. In D. Milanović & G. Sporiš (Eds.), 7th International Scientific Conference on Kinesiology: Fundamental and Applied Kinesiology - Steps Forward : Proceedings (pp. 537–539). Amsterdam University Press.
Richards, G., & Browne, W. V. (2022). Prenatal testosterone and sexually differentiated childhood play preferences: a meta-analysis of amniotic fluid studies. Current Psychology. https://doi.org/10.1007/s12144-021-02386-z
Ritchie, H., & Roser, M. (2019, June 13). Gender Ratio. Our World in Data. Retrieved June 27, 2022, from https://ourworldindata.org/gender-ratio#sex-ratio-through-adulthood
Schmitt, D. P. (2005). Measuring sociosexuality across people and nations: Revisiting the strengths and weaknesses of cross-cultural sex research. Behavioral and Brain Sciences, 28(2), 297–304. https://doi.org/10.1017/s0140525x05440054
Schmitt, D. P., Long, A. E., McPhearson, A., O’Brien, K., Remmert, B., & Shah, S. H. (2016). Personality and gender differences in global perspective. International Journal of Psychology, 52, 45–56. https://doi.org/10.1002/ijop.12265
Schmitt, D. P., Realo, A., Voracek, M., & Allik, J. (2008). Why can’t a man be more like a woman? Sex differences in Big Five personality traits across 55 cultures. Journal of Personality and Social Psychology, 94(1), 168–182. https://doi.org/10.1037/0022-3514.94.1.168
Schwartz, S. H., & Rubel, T. (2005). Sex differences in value priorities: Cross-cultural and multimethod studies. Journal of Personality and Social Psychology, 89(6), 1010–1028. https://doi.org/10.1037/0022-3514.89.6.1010
Shams, R., & Afghari, A. (2011). Effects of Culture and Gender in Comprehension of Speech Acts of Indirect Request. English Language Teaching, 4(4). https://doi.org/10.5539/elt.v4n4p279
Simpson, E. A., Nicolini, Y., Shetler, M., Suomi, S. J., Ferrari, P. F., & Paukner, A. (2016). Experience-independent sex differences in newborn macaques: Females are more social than males. Scientific Reports, 6(1). https://doi.org/10.1038/srep19669
Stoet, G., & Geary, D. C. (2018). The Gender-Equality Paradox in Science, Technology, Engineering, and Mathematics Education. Psychological Science, 29(4), 581–593. https://doi.org/10.1177/0956797617741719
Stoet, G., & Geary, D. C. (2020). The Gender-Equality Paradox Is Part of a Bigger Phenomenon: Reply to Richardson and Colleagues (2020). Psychological Science, 31(3), 342–344. https://doi.org/10.1177/0956797620904134
Su, R., Rounds, J., & Armstrong, P. I. (2009). Men and things, women and people: A meta-analysis of sex differences in interests. Psychological Bulletin, 135(6), 859–884. https://doi.org/10.1037/a0017364
Todor, I. (2014). Investigating “The Old Stereotype” about Boys/Girls and Mathematics: Gender Differences in Implicit Theory of Intelligence and Mathematics Self-efficacy Beliefs. Procedia - Social and Behavioral Sciences, 159, 319–323. https://doi.org/10.1016/j.sbspro.2014.12.380
Vandermassen, G. (2010). Evolution and Rape: A Feminist Darwinian Perspective. Sex Roles, 64(9–10), 732–747. https://doi.org/10.1007/s11199-010-9895-y
Walton, G. M., Spencer, S. J., & Erman, S. (2013). Affirmative Meritocracy. Social Issues and Policy Review, 7(1), 1–35. https://doi.org/10.1111/j.1751-2409.2012.01041.x
Weisberg, Y. J., DeYoung, C. G., & Hirsh, J. B. (2011). Gender Differences in Personality across the Ten Aspects of the Big Five. Frontiers in Psychology, 2. https://doi.org/10.3389/fpsyg.2011.00178
Wilson, T. D., Reinhard, D. A., Westgate, E. C., Gilbert, D. T., Ellerbeck, N., Hahn, C., Brown, C. L., & Shaked, A. (2014). Just think: The challenges of the disengaged mind. Science, 345(6192), 75–77. https://doi.org/10.1126/science.1250830
World Health Organization. (2021, October 4). Ageing and health. Retrieved June 27, 2022, from https://www.who.int/news-room/fact-sheets/detail/ageing-and-health

`;

}

